//! PCAP file reader — parses libpcap/tcpdump capture files
//!
//! Supports standard PCAP format (magic 0xa1b2c3d4) with Ethernet link type.
//! Extracts raw Ethernet frames for use as cocotb test stimulus.

use anyhow::{Context, Result};
use std::path::Path;

/// A single captured Ethernet frame
#[derive(Debug, Clone)]
pub struct PcapPacket {
    /// Timestamp seconds
    pub ts_sec: u32,
    /// Timestamp microseconds
    pub ts_usec: u32,
    /// Raw Ethernet frame data
    pub data: Vec<u8>,
}

/// Read packets from a PCAP file
pub fn read_pcap(path: &Path) -> Result<Vec<PcapPacket>> {
    let data = std::fs::read(path)
        .with_context(|| format!("Failed to read PCAP file: {}", path.display()))?;

    if data.len() < 24 {
        anyhow::bail!("PCAP file too small ({} bytes, need at least 24)", data.len());
    }

    // Parse global header
    let magic = u32::from_le_bytes([data[0], data[1], data[2], data[3]]);
    let (is_le, _is_ns) = match magic {
        0xa1b2c3d4 => (true, false),    // Little-endian, microseconds
        0xd4c3b2a1 => (false, false),   // Big-endian, microseconds
        0xa1b23c4d => (true, true),     // Little-endian, nanoseconds
        0x4d3cb2a1 => (false, true),    // Big-endian, nanoseconds
        _ => anyhow::bail!("Not a valid PCAP file (magic: 0x{:08x})", magic),
    };

    let read_u32 = |offset: usize| -> u32 {
        let b = [data[offset], data[offset+1], data[offset+2], data[offset+3]];
        if is_le { u32::from_le_bytes(b) } else { u32::from_be_bytes(b) }
    };

    let _version_major = read_u32(4) & 0xFFFF;
    let _version_minor = (read_u32(4) >> 16) & 0xFFFF;
    let snap_len = read_u32(16);
    let link_type = read_u32(20);

    if link_type != 1 {
        anyhow::bail!("PCAP link type {} not supported (only Ethernet/1 is supported)", link_type);
    }

    let _ = snap_len; // We'll use the actual captured length

    // Parse packets
    let mut packets = Vec::new();
    let mut offset = 24; // Skip global header

    while offset + 16 <= data.len() {
        let ts_sec = read_u32(offset);
        let ts_usec = read_u32(offset + 4);
        let incl_len = read_u32(offset + 8) as usize;
        let _orig_len = read_u32(offset + 12) as usize;
        offset += 16;

        if offset + incl_len > data.len() {
            break; // Truncated packet
        }

        packets.push(PcapPacket {
            ts_sec,
            ts_usec,
            data: data[offset..offset + incl_len].to_vec(),
        });

        offset += incl_len;
    }

    Ok(packets)
}

/// Generate Python cocotb test stimulus from PCAP packets
pub fn generate_stimulus(packets: &[PcapPacket]) -> String {
    let mut out = String::new();
    out.push_str("# PCAP-imported test stimulus\n");
    out.push_str("# Generated by pacgate — do not edit\n\n");
    out.push_str("# Each entry is a raw Ethernet frame as a list of bytes\n");
    out.push_str("PCAP_FRAMES = [\n");

    for (i, pkt) in packets.iter().enumerate() {
        out.push_str(&format!("    # Frame {} ({} bytes, ts={}.{})\n",
            i, pkt.data.len(), pkt.ts_sec, pkt.ts_usec));

        // Extract basic info for comment
        if pkt.data.len() >= 14 {
            let dst_mac = format!("{:02x}:{:02x}:{:02x}:{:02x}:{:02x}:{:02x}",
                pkt.data[0], pkt.data[1], pkt.data[2], pkt.data[3], pkt.data[4], pkt.data[5]);
            let src_mac = format!("{:02x}:{:02x}:{:02x}:{:02x}:{:02x}:{:02x}",
                pkt.data[6], pkt.data[7], pkt.data[8], pkt.data[9], pkt.data[10], pkt.data[11]);
            let ethertype = u16::from_be_bytes([pkt.data[12], pkt.data[13]]);
            out.push_str(&format!("    # dst={} src={} ethertype=0x{:04x}\n",
                dst_mac, src_mac, ethertype));
        }

        out.push_str("    [");
        for (j, byte) in pkt.data.iter().enumerate() {
            if j > 0 && j % 16 == 0 {
                out.push_str("\n     ");
            }
            if j > 0 { out.push_str(", "); }
            out.push_str(&format!("0x{:02x}", byte));
        }
        out.push_str("],\n");
    }

    out.push_str("]\n");
    out
}

/// Print PCAP summary (human-readable)
pub fn print_summary(packets: &[PcapPacket]) {
    println!("PCAP Summary: {} frames", packets.len());
    println!();
    println!("  # Size   Dst MAC            Src MAC            EtherType");
    println!("  — ————   ——————————————————  ——————————————————  —————————");

    for (i, pkt) in packets.iter().enumerate() {
        if pkt.data.len() >= 14 {
            let dst_mac = format!("{:02x}:{:02x}:{:02x}:{:02x}:{:02x}:{:02x}",
                pkt.data[0], pkt.data[1], pkt.data[2], pkt.data[3], pkt.data[4], pkt.data[5]);
            let src_mac = format!("{:02x}:{:02x}:{:02x}:{:02x}:{:02x}:{:02x}",
                pkt.data[6], pkt.data[7], pkt.data[8], pkt.data[9], pkt.data[10], pkt.data[11]);
            let ethertype = u16::from_be_bytes([pkt.data[12], pkt.data[13]]);
            let et_name = match ethertype {
                0x0800 => "IPv4",
                0x0806 => "ARP",
                0x86DD => "IPv6",
                0x8100 => "802.1Q",
                0x88CC => "LLDP",
                0x88A4 => "EtherCAT",
                0x8892 => "PROFINET",
                0x88F7 => "PTP",
                _ => "",
            };
            println!("  {} {:>5}  {}  {}  0x{:04X} {}",
                i + 1, pkt.data.len(), dst_mac, src_mac, ethertype, et_name);
        } else {
            println!("  {} {:>5}  (truncated)", i + 1, pkt.data.len());
        }

        if i >= 49 {
            println!("  ... ({} more frames)", packets.len() - 50);
            break;
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Create a minimal valid PCAP file with one Ethernet frame
    fn make_pcap(frames: &[&[u8]]) -> Vec<u8> {
        let mut data = Vec::new();
        // Global header (24 bytes)
        data.extend_from_slice(&0xa1b2c3d4u32.to_le_bytes()); // magic
        data.extend_from_slice(&2u16.to_le_bytes()); // version major
        data.extend_from_slice(&4u16.to_le_bytes()); // version minor
        data.extend_from_slice(&0i32.to_le_bytes()); // thiszone
        data.extend_from_slice(&0u32.to_le_bytes()); // sigfigs
        data.extend_from_slice(&65535u32.to_le_bytes()); // snaplen
        data.extend_from_slice(&1u32.to_le_bytes()); // link type (Ethernet)

        for (i, frame) in frames.iter().enumerate() {
            // Per-packet header (16 bytes)
            data.extend_from_slice(&(i as u32).to_le_bytes()); // ts_sec
            data.extend_from_slice(&0u32.to_le_bytes()); // ts_usec
            data.extend_from_slice(&(frame.len() as u32).to_le_bytes()); // incl_len
            data.extend_from_slice(&(frame.len() as u32).to_le_bytes()); // orig_len
            data.extend_from_slice(frame);
        }

        data
    }

    #[test]
    fn parse_single_frame() {
        // Minimal Ethernet frame: 14-byte header + 46-byte payload
        let frame = [0xffu8; 60]; // broadcast, 60 bytes
        let pcap_data = make_pcap(&[&frame]);

        let tmp = tempfile::NamedTempFile::new().unwrap();
        std::fs::write(tmp.path(), &pcap_data).unwrap();

        let packets = read_pcap(tmp.path()).unwrap();
        assert_eq!(packets.len(), 1);
        assert_eq!(packets[0].data.len(), 60);
    }

    #[test]
    fn parse_multiple_frames() {
        let frame1 = [0xaau8; 64];
        let frame2 = [0xbbu8; 128];
        let pcap_data = make_pcap(&[&frame1, &frame2]);

        let tmp = tempfile::NamedTempFile::new().unwrap();
        std::fs::write(tmp.path(), &pcap_data).unwrap();

        let packets = read_pcap(tmp.path()).unwrap();
        assert_eq!(packets.len(), 2);
        assert_eq!(packets[0].data.len(), 64);
        assert_eq!(packets[1].data.len(), 128);
    }

    #[test]
    fn reject_too_small() {
        let tmp = tempfile::NamedTempFile::new().unwrap();
        std::fs::write(tmp.path(), &[0u8; 10]).unwrap();
        assert!(read_pcap(tmp.path()).is_err());
    }

    #[test]
    fn reject_bad_magic() {
        let tmp = tempfile::NamedTempFile::new().unwrap();
        std::fs::write(tmp.path(), &[0u8; 24]).unwrap();
        assert!(read_pcap(tmp.path()).is_err());
    }

    #[test]
    fn generate_stimulus_output() {
        let packets = vec![
            PcapPacket {
                ts_sec: 0,
                ts_usec: 0,
                data: vec![0xff, 0xff, 0xff, 0xff, 0xff, 0xff, // dst
                           0x00, 0x11, 0x22, 0x33, 0x44, 0x55, // src
                           0x08, 0x06, // ARP
                           0x00, 0x01], // payload
            },
        ];
        let stim = generate_stimulus(&packets);
        assert!(stim.contains("PCAP_FRAMES"));
        assert!(stim.contains("0xff, 0xff, 0xff, 0xff, 0xff, 0xff"));
        assert!(stim.contains("ethertype=0x0806"));
    }
}
