# JSON Schema for PacGate rule files (expressed in YAML)
type: object
required: [pacgate]
properties:
  pacgate:
    type: object
    required: [version, defaults, rules]
    properties:
      version:
        type: string
        enum: ["1.0"]
      defaults:
        type: object
        required: [action]
        properties:
          action:
            type: string
            enum: [pass, drop]
      rules:
        type: array
        minItems: 1
        items:
          type: object
          required: [name, priority, match, action]
          properties:
            name:
              type: string
              pattern: "^[a-z_][a-z0-9_]*$"
            type:
              type: string
              enum: [stateless, stateful]
            priority:
              type: integer
              minimum: 0
              maximum: 65535
            match:
              type: object
              properties:
                dst_mac:
                  type: string
                  pattern: "^([0-9a-fA-F]{2}|\\*)(:[0-9a-fA-F]{2}|:\\*){5}$"
                src_mac:
                  type: string
                  pattern: "^([0-9a-fA-F]{2}|\\*)(:[0-9a-fA-F]{2}|:\\*){5}$"
                ethertype:
                  type: string
                  pattern: "^0x[0-9a-fA-F]{4}$"
                vlan_id:
                  type: integer
                  minimum: 0
                  maximum: 4095
                vlan_pcp:
                  type: integer
                  minimum: 0
                  maximum: 7
            action:
              type: string
              enum: [pass, drop]
